modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="elytramod"
version="${mod_version}"
displayName="Flight of the Elytra"
description='''Adds animated custom elytra.'''
authors="Daedra"

[[dependencies.elytramod]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.elytramod]]
modId="geckolib3"
mandatory=true
versionRange="[3.1.40,)"
ordering="AFTER"
side="BOTH"
